"""initial schema (Модуль 9: все таблицы BetSignals)

Revision ID: 0001_initial
Revises: 
Create Date: 2026-10-08 07:37:38.951532
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# JSONB в PostgreSQL, обычный JSON — в остальных диалектах (нужно для тестов на sqlite)
JSONB = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensemble_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('w_llm', sa.Float(), nullable=False),
    sa.Column('w_stat', sa.Float(), nullable=False),
    sa.Column('brier_llm', sa.Float(), nullable=True),
    sa.Column('brier_stat', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ensemble_weights_sport'), 'ensemble_weights', ['sport'], unique=True)
    op.create_table('league_calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('league', sa.String(length=160), nullable=False),
    sa.Column('market', sa.String(length=24), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('calibration', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'league', 'market', name='uq_calibration_key')
    )
    op.create_index(op.f('ix_league_calibration_league'), 'league_calibration', ['league'], unique=False)
    op.create_index(op.f('ix_league_calibration_sport'), 'league_calibration', ['sport'], unique=False)
    op.create_table('league_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('league', sa.String(length=160), nullable=False),
    sa.Column('insights_json', JSONB, nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insights_sport_league_active', 'league_insights', ['sport', 'league', 'active'], unique=False)
    op.create_index(op.f('ix_league_insights_league'), 'league_insights', ['league'], unique=False)
    op.create_index(op.f('ix_league_insights_sport'), 'league_insights', ['sport'], unique=False)
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_code'), 'sports', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'canonical_name', name='uq_team_sport_name')
    )
    op.create_index(op.f('ix_teams_sport_id'), 'teams', ['sport_id'], unique=False)
    op.create_table('elo_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=60), nullable=True),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('matches_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'team_id', 'map_name', name='uq_elo_team_map')
    )
    op.create_index(op.f('ix_elo_ratings_sport_id'), 'elo_ratings', ['sport_id'], unique=False)
    op.create_index(op.f('ix_elo_ratings_team_id'), 'elo_ratings', ['team_id'], unique=False)
    op.create_index('ix_elo_sport_map', 'elo_ratings', ['sport_id', 'map_name'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sa.String(length=120), nullable=False),
    sa.Column('league', sa.String(length=160), nullable=False),
    sa.Column('league_tier', sa.String(length=40), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_home', sa.Integer(), nullable=True),
    sa.Column('result_away', sa.Integer(), nullable=True),
    sa.Column('is_market_moves', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('data_quality', sa.String(length=10), server_default='ok', nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('external_refs', JSONB, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'ext_id', name='uq_match_ext')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index('ix_matches_fixture', 'matches', ['sport_id', 'home_team_id', 'away_team_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_league'), 'matches', ['league'], unique=False)
    op.create_index(op.f('ix_matches_sport_id'), 'matches', ['sport_id'], unique=False)
    op.create_index('ix_matches_start_status', 'matches', ['starts_at', 'status'], unique=False)
    op.create_index(op.f('ix_matches_starts_at'), 'matches', ['starts_at'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'source', name='uq_alias_source')
    )
    op.create_index('ix_team_aliases_alias_lower', 'team_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_team_aliases_team_id'), 'team_aliases', ['team_id'], unique=False)
    op.create_table('xg_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('payload', JSONB, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'source', name='uq_xg_team_source')
    )
    op.create_index(op.f('ix_xg_cache_team_id'), 'xg_cache', ['team_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('pass_no', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('parsed', JSONB, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_match_id'), 'analyses', ['match_id'], unique=False)
    op.create_index('ix_analyses_match_level', 'analyses', ['match_id', 'level', 'pass_no'], unique=False)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=24), nullable=False),
    sa.Column('selection', sa.String(length=24), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_captured_at'), 'odds', ['captured_at'], unique=False)
    op.create_index('ix_odds_lookup', 'odds', ['match_id', 'market', 'selection', 'captured_at'], unique=False)
    op.create_index('ix_odds_match_captured', 'odds', ['match_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_odds_match_id'), 'odds', ['match_id'], unique=False)
    op.create_index(op.f('ix_odds_source'), 'odds', ['source'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=24), nullable=False),
    sa.Column('selection', sa.String(length=24), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('prob_final', sa.Float(), nullable=False),
    sa.Column('prob_implied', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('stake_pct', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('key_factors', JSONB, nullable=False),
    sa.Column('risk_notes', JSONB, nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('judge_reason', sa.Text(), nullable=True),
    sa.Column('is_live', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('live_stage', sa.String(length=80), nullable=True),
    sa.Column('pass_no', sa.Integer(), nullable=True),
    sa.Column('odds_source', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_edge'), 'signals', ['edge'], unique=False)
    op.create_index(op.f('ix_signals_match_id'), 'signals', ['match_id'], unique=False)
    op.create_index('ix_signals_match_market', 'signals', ['match_id', 'market', 'selection', 'line'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index('ix_signals_status_created', 'signals', ['status', 'created_at'], unique=False)
    op.create_table('stat_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('parsed', JSONB, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_predictions_match_id'), 'stat_predictions', ['match_id'], unique=False)
    op.create_table('judge_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=False),
    sa.Column('red_flags', JSONB, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_verdicts_match_id'), 'judge_verdicts', ['match_id'], unique=False)
    op.create_index(op.f('ix_judge_verdicts_signal_id'), 'judge_verdicts', ['signal_id'], unique=False)
    op.create_index(op.f('ix_judge_verdicts_verdict'), 'judge_verdicts', ['verdict'], unique=False)
    op.create_table('user_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'user_id', name='uq_delivery_signal_user')
    )
    op.create_index(op.f('ix_user_deliveries_signal_id'), 'user_deliveries', ['signal_id'], unique=False)
    op.create_index(op.f('ix_user_deliveries_user_id'), 'user_deliveries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deliveries_user_id'), table_name='user_deliveries')
    op.drop_index(op.f('ix_user_deliveries_signal_id'), table_name='user_deliveries')
    op.drop_table('user_deliveries')
    op.drop_index(op.f('ix_judge_verdicts_verdict'), table_name='judge_verdicts')
    op.drop_index(op.f('ix_judge_verdicts_signal_id'), table_name='judge_verdicts')
    op.drop_index(op.f('ix_judge_verdicts_match_id'), table_name='judge_verdicts')
    op.drop_table('judge_verdicts')
    op.drop_index(op.f('ix_stat_predictions_match_id'), table_name='stat_predictions')
    op.drop_table('stat_predictions')
    op.drop_index('ix_signals_status_created', table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index('ix_signals_match_market', table_name='signals')
    op.drop_index(op.f('ix_signals_match_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_edge'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_odds_source'), table_name='odds')
    op.drop_index(op.f('ix_odds_match_id'), table_name='odds')
    op.drop_index('ix_odds_match_captured', table_name='odds')
    op.drop_index('ix_odds_lookup', table_name='odds')
    op.drop_index(op.f('ix_odds_captured_at'), table_name='odds')
    op.drop_table('odds')
    op.drop_index('ix_analyses_match_level', table_name='analyses')
    op.drop_index(op.f('ix_analyses_match_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_xg_cache_team_id'), table_name='xg_cache')
    op.drop_table('xg_cache')
    op.drop_index(op.f('ix_team_aliases_team_id'), table_name='team_aliases')
    op.drop_index('ix_team_aliases_alias_lower', table_name='team_aliases')
    op.drop_table('team_aliases')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_starts_at'), table_name='matches')
    op.drop_index('ix_matches_start_status', table_name='matches')
    op.drop_index(op.f('ix_matches_sport_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_league'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index('ix_matches_fixture', table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_elo_sport_map', table_name='elo_ratings')
    op.drop_index(op.f('ix_elo_ratings_team_id'), table_name='elo_ratings')
    op.drop_index(op.f('ix_elo_ratings_sport_id'), table_name='elo_ratings')
    op.drop_table('elo_ratings')
    op.drop_index(op.f('ix_teams_sport_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sports_code'), table_name='sports')
    op.drop_table('sports')
    op.drop_index(op.f('ix_league_insights_sport'), table_name='league_insights')
    op.drop_index(op.f('ix_league_insights_league'), table_name='league_insights')
    op.drop_index('ix_insights_sport_league_active', table_name='league_insights')
    op.drop_table('league_insights')
    op.drop_index(op.f('ix_league_calibration_sport'), table_name='league_calibration')
    op.drop_index(op.f('ix_league_calibration_league'), table_name='league_calibration')
    op.drop_table('league_calibration')
    op.drop_index(op.f('ix_ensemble_weights_sport'), table_name='ensemble_weights')
    op.drop_table('ensemble_weights')
    # ### end Alembic commands ###
